import assert from 'node:assert/strict';
import {readFile,writeFile,unlink,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {startFixture} from '../fixture/server.mjs';
import {evaluate} from './evaluate.mjs';
import {safeJson} from './build-report.mjs';
const dir=path.resolve('report');
const imported=await import(process.env.PLAYWRIGHT_PACKAGE?pathToFileURL(process.env.PLAYWRIGHT_PACKAGE).href:'playwright');
const pw=imported.chromium?imported:imported.default;
const template=await readFile('ui/report.html','utf8'), data=JSON.parse(await readFile(path.join(dir,'results.json'),'utf8'));
const variants={empty:{...data,cases:[]},error:structuredClone(data)};
variants.error.cases[0].status='error';variants.error.cases[0].message='Injected QA transport failure';
for(const[name,d]of Object.entries(variants))await writeFile(path.join(dir,`qa-${name}.html`),template.replace('/*__PROBE_DATA__*/null',safeJson({data:d,summary:evaluate(d)})));
await writeFile(path.join(dir,'qa-missing.html'),template);
await writeFile(path.join(dir,'qa-public.html'),template.replace('/*__PROBE_DATA__*/null',safeJson({publicSnapshot:true,data,summary:evaluate(data)})));
const fixture=await startFixture({reportDir:dir}),browser=await pw.chromium.launch({headless:true});
const checks=[];
try {
 const page=await browser.newPage({viewport:{width:1280,height:900}}), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(fixture.url+'/report/');
 assert.equal(await page.locator('.card').count(),3);assert.equal(await page.locator('#defects').innerText(),'3 / 3');
 await page.locator('#filter').selectOption('all');assert.equal(await page.locator('.card').count(),5);
 await page.locator('#filter').selectOption('pass');assert.equal(await page.locator('.card').count(),2);
 await page.locator('#filter').selectOption('violation');
 await page.locator('summary').first().click();
 const pictures=page.locator('.evidence img');
 assert.equal(await pictures.count(),6);
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('details[open] img')).every(img=>img.complete&&img.naturalWidth>0));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mkdir('docs',{recursive:true});
 await page.screenshot({path:'docs/preview.png',fullPage:true});checks.push('Desktop: counts, filters, representative evidence images, no page overflow');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'docs/preview-mobile.png',fullPage:true});checks.push('Mobile 390 px: no page overflow, cards and filters remain available');
 await page.goto(fixture.url+'/report/qa-empty.html');assert.match(await page.locator('#state').innerText(),/아직 검사 결과가 없습니다/);assert.equal(await page.locator('#content').isVisible(),false);checks.push('Empty result: explanatory state with result panels hidden');
 await page.goto(fixture.url+'/report/qa-error.html');assert.match(await page.locator('#state').innerText(),/검증 기준을 충족하지/);assert.equal(await page.locator('#errors').innerText(),'1회');checks.push('Execution error: visible warning and separate failure count');
 await page.goto(fixture.url+'/report/qa-missing.html');assert.match(await page.locator('#state').innerText(),/결과를 읽지 못했습니다/);checks.push('Missing embedded data: explanatory error state');
 await page.goto(fixture.url+'/report/qa-public.html');await page.locator('summary').first().click();assert.equal(await page.locator('.evidence img').count(),0);assert.match(await page.locator('details[open]').innerText(),/로컬 재실행 후/);checks.push('Public text snapshot: numeric findings and steps without media links');
 assert.deepEqual(errors,[]);
 await writeFile(path.join(dir,'ui-qa.json'),JSON.stringify({passed:true,checks,scriptErrors:errors,browser:browser.version()},null,2)+'\n');
 console.log(JSON.stringify({passed:true,checks:checks.length}));
}finally{await browser.close();await fixture.close();for(const name of ['empty','error','missing','public'])await unlink(path.join(dir,`qa-${name}.html`));}
